### ISSUE TITLE
Hello world flask_app

### ISSUE THREAD

**Issue by ndanielsen** [samxj/gutenberg_scifi#9]
But instead of 'hello world,' return a list of a few books that you have on file. 

This is is a great starting place: 
https://devcenter.heroku.com/articles/getting-started-with-python-o

**Comment by skasim** [comment]
After the last session, my app wasn't working, so I started from scratch and it is working now, but it only gives one author, so I wanted to return the entire list of authors. I unit tested the code I wrote in IPython Notebook and it works fine, but when I try to deploy it Heroku, I get an Internal Server Error. I am not sure exactly what the issue is. I tried looking at the issue logs, but I couldn't make sense of them.

**Comment by skasim** [comment]
i found this flask deployment guide that is pretty helpful: http://www.fullstackpython.com/flask.html

**Comment by ndanielsen** [comment]
Sometimes heroku doesn't like to run static files. There are ways around it, but in general amazon s3 is the way to go. We can review togetehr tomorrow
